import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useAutoRefresh } from "@/hooks/useAutoRefresh";
import { operatorStatementService } from "@/services/operatorStatementService";
import type { OperatorStatement } from "@/types/operatorStatement";

type SortField = "statementNo" | "busOperatorId" | "netAmount" | "fromDate" | "updatedAtUtc";
type SortDir = "asc" | "desc";
type StatusFilter = "all" | "Draft" | "Approved" | "Paid" | "Cancelled";

const PAGE_SIZES = [10, 25, 50];

function money(n: number) {
  return n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function statusBadge(status: string) {
  const map: Record<string, string> = {
    Draft: "bg-secondary",
    Approved: "bg-info",
    Paid: "bg-success",
    Cancelled: "bg-danger",
  };
  return <span className={`badge ${map[status] ?? "bg-secondary"}`}>{status}</span>;
}

export default function OperatorStatementList() {
  const { data, loading, error, lastSyncedAt, reload } = useAutoRefresh<OperatorStatement[]>(
    () => operatorStatementService.getAll(),
    5000
  );

  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [sortField, setSortField] = useState<SortField>("updatedAtUtc");
  const [sortDir, setSortDir] = useState<SortDir>("desc");
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const statements = data ?? [];

  const stats = useMemo(() => {
    const total = statements.length;
    const platformPayable = statements.reduce((s, x) => s + x.platformPayableToOperator, 0);
    const operatorPayable = statements.reduce((s, x) => s + x.operatorPayableToPlatform, 0);
    const draftCount = statements.filter((x) => x.status === "Draft").length;
    return { total, platformPayable, operatorPayable, draftCount };
  }, [statements]);

  const filtered = useMemo(() => {
    let list = statements;
    if (statusFilter !== "all") list = list.filter((x) => x.status === statusFilter);
    if (search.trim()) {
      const q = search.trim().toLowerCase();
      list = list.filter(
        (x) => x.busOperatorId.toLowerCase().includes(q) || x.statementNo.toLowerCase().includes(q)
      );
    }
    const sorted = [...list].sort((a, b) => {
      let cmp = 0;
      if (sortField === "statementNo") cmp = a.statementNo.localeCompare(b.statementNo);
      else if (sortField === "busOperatorId") cmp = a.busOperatorId.localeCompare(b.busOperatorId);
      else if (sortField === "fromDate") cmp = a.fromDate.localeCompare(b.fromDate);
      else if (sortField === "updatedAtUtc")
        cmp = (a.updatedAtUtc ?? a.createdAtUtc).localeCompare(b.updatedAtUtc ?? b.createdAtUtc);
      else cmp = a[sortField] - b[sortField];
      return sortDir === "asc" ? cmp : -cmp;
    });
    return sorted;
  }, [statements, statusFilter, search, sortField, sortDir]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const pageSafe = Math.min(page, totalPages);
  const pageItems = filtered.slice((pageSafe - 1) * pageSize, pageSafe * pageSize);

  function toggleSort(field: SortField) {
    if (field === sortField) setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    else {
      setSortField(field);
      setSortDir("asc");
    }
    setPage(1);
  }

  function sortIcon(field: SortField) {
    if (field !== sortField) return <i className="fa-solid fa-sort text-muted ms-1" />;
    return <i className={`fa-solid fa-sort-${sortDir === "asc" ? "up" : "down"} ms-1`} />;
  }

  return (
    <div className="container-fluid py-3">
      <nav aria-label="breadcrumb">
        <ol className="breadcrumb mb-2">
          <li className="breadcrumb-item">
            <Link to="/admin">Admin</Link>
          </li>
          <li className="breadcrumb-item active">Operator Statements</li>
        </ol>
      </nav>

      <div className="d-flex justify-content-between align-items-start flex-wrap mb-3">
        <div>
          <h4 className="mb-1">
            <i className="fa-solid fa-file-invoice me-2 text-primary" />
            Operator Statements
          </h4>
          <div className="text-muted small">
            <span className="badge bg-success-subtle text-success border border-success-subtle me-2">
              <i className="fa-solid fa-circle fa-2xs me-1" /> Live
            </span>
            api/OperatorStatements — last synced{" "}
            {lastSyncedAt ? lastSyncedAt.toLocaleTimeString() : "—"}
            <span className="ms-2">
              <i className="fa-solid fa-lock me-1" /> read-only — generated by settlements only
            </span>
          </div>
        </div>
        <button className="btn btn-outline-secondary" onClick={() => reload()} disabled={loading}>
          <i className={`fa-solid fa-rotate ${loading ? "fa-spin" : ""}`} />
        </button>
      </div>

      {error && (
        <div className="alert alert-danger d-flex align-items-center">
          <i className="fa-solid fa-triangle-exclamation me-2" /> {error}
        </div>
      )}

      <div className="row g-3 mb-3">
        <StatCard label="Total Statements" value={stats.total} color="bg-primary" />
        <StatCard label="Platform Payable" value={`BDT ${money(stats.platformPayable)}`} color="bg-warning" />
        <StatCard label="Operator Payable" value={`BDT ${money(stats.operatorPayable)}`} color="bg-info" />
        <StatCard label="Draft" value={stats.draftCount} color="bg-secondary" />
      </div>

      <div className="card shadow-sm">
        <div className="card-body">
          <div className="row g-2 align-items-center mb-3">
            <div className="col-12 col-md-5">
              <div className="input-group">
                <span className="input-group-text bg-white">
                  <i className="fa-solid fa-magnifying-glass" />
                </span>
                <input
                  className="form-control"
                  placeholder="Search by Statement No / Bus Operator ID..."
                  value={search}
                  onChange={(e) => {
                    setSearch(e.target.value);
                    setPage(1);
                  }}
                />
              </div>
            </div>
            <div className="col-6 col-md-3">
              <select
                className="form-select"
                value={statusFilter}
                onChange={(e) => {
                  setStatusFilter(e.target.value as StatusFilter);
                  setPage(1);
                }}
              >
                <option value="all">All Statuses</option>
                <option value="Draft">Draft</option>
                <option value="Approved">Approved</option>
                <option value="Paid">Paid</option>
                <option value="Cancelled">Cancelled</option>
              </select>
            </div>
            <div className="col-6 col-md-2">
              <select
                className="form-select"
                value={pageSize}
                onChange={(e) => {
                  setPageSize(Number(e.target.value));
                  setPage(1);
                }}
              >
                {PAGE_SIZES.map((s) => (
                  <option key={s} value={s}>
                    {s} / page
                  </option>
                ))}
              </select>
            </div>
            <div className="col-12 col-md-2 text-md-end text-muted small">
              {filtered.length} / {statements.length}
            </div>
          </div>

          <div className="table-responsive">
            <table className="table table-hover align-middle">
              <thead>
                <tr>
                  <th role="button" onClick={() => toggleSort("statementNo")}>
                    Statement No {sortIcon("statementNo")}
                  </th>
                  <th role="button" onClick={() => toggleSort("busOperatorId")}>
                    Bus Operator ID {sortIcon("busOperatorId")}
                  </th>
                  <th role="button" onClick={() => toggleSort("fromDate")}>
                    Period {sortIcon("fromDate")}
                  </th>
                  <th className="text-end" role="button" onClick={() => toggleSort("netAmount")}>
                    Net Amount {sortIcon("netAmount")}
                  </th>
                  <th>Direction</th>
                  <th>Status</th>
                  <th role="button" onClick={() => toggleSort("updatedAtUtc")}>
                    Last Updated {sortIcon("updatedAtUtc")}
                  </th>
                  <th className="text-end">Actions</th>
                </tr>
              </thead>
              <tbody>
                {loading && !data && (
                  <tr>
                    <td colSpan={8} className="text-center py-4 text-muted">
                      <i className="fa-solid fa-spinner fa-spin me-2" /> Loading...
                    </td>
                  </tr>
                )}
                {!loading && pageItems.length === 0 && (
                  <tr>
                    <td colSpan={8} className="text-center py-4 text-muted">
                      No operator statements found.
                    </td>
                  </tr>
                )}
                {pageItems.map((s) => (
                  <tr key={s.id}>
                    <td className="fw-semibold">{s.statementNo}</td>
                    <td className="text-truncate" style={{ maxWidth: 200 }} title={s.busOperatorId}>
                      {s.busOperatorId}
                    </td>
                    <td className="text-muted small">
                      {s.fromDate} → {s.toDate}
                    </td>
                    <td className="text-end">{money(s.netAmount)}</td>
                    <td className="text-muted small">{s.netDirection}</td>
                    <td>{statusBadge(s.status)}</td>
                    <td className="text-muted small">
                      {new Date(s.updatedAtUtc ?? s.createdAtUtc).toLocaleString()}
                    </td>
                    <td className="text-end">
                      <Link
                        className="btn btn-outline-secondary btn-sm"
                        to={`/admin/resource/OperatorStatements/${s.id}`}
                        title="Details"
                      >
                        <i className="fa-solid fa-eye" />
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {totalPages > 1 && (
            <nav className="d-flex justify-content-end">
              <ul className="pagination pagination-sm mb-0">
                <li className={`page-item ${pageSafe === 1 ? "disabled" : ""}`}>
                  <button className="page-link" onClick={() => setPage((p) => Math.max(1, p - 1))}>
                    <i className="fa-solid fa-chevron-left" />
                  </button>
                </li>
                {Array.from({ length: totalPages }, (_, i) => i + 1).map((p) => (
                  <li key={p} className={`page-item ${p === pageSafe ? "active" : ""}`}>
                    <button className="page-link" onClick={() => setPage(p)}>
                      {p}
                    </button>
                  </li>
                ))}
                <li className={`page-item ${pageSafe === totalPages ? "disabled" : ""}`}>
                  <button
                    className="page-link"
                    onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  >
                    <i className="fa-solid fa-chevron-right" />
                  </button>
                </li>
              </ul>
            </nav>
          )}
        </div>
      </div>
    </div>
  );
}

function StatCard({ label, value, color }: { label: string; value: string | number; color: string }) {
  return (
    <div className="col-6 col-md-3">
      <div className={`card text-white ${color} shadow-sm`}>
        <div className="card-body py-3">
          <div className="text-uppercase small opacity-75">{label}</div>
          <div className="fs-5 fw-bold">{value}</div>
        </div>
      </div>
    </div>
  );
}