// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.BusFleet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    // Which BusAmenity is on which Bus. Read is open to any logged-in user (shown on bus
    // detail/search pages), writes are Admin-only for the same reason as BusAmenitiesController.
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class BusAmenityMappingsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.BusAmenityMappings.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.BusAmenityMappings.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(BusAmenityMappingCreateDto dto)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = new BusAmenityMapping
            {
                BusId = dto.BusId,
                BusAmenityId = dto.BusAmenityId,
            };

            db.BusAmenityMappings.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, BusAmenityMappingUpdateDto dto)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = await db.BusAmenityMappings.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "BusAmenityMapping not found." });

            item.BusId = dto.BusId;
            item.BusAmenityId = dto.BusAmenityId;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This BusAmenityMapping was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save BusAmenityMapping.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = await db.BusAmenityMappings.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            db.BusAmenityMappings.Remove(item);

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This BusAmenityMapping was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this BusAmenityMapping — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static BusAmenityMappingResponseDto ToResponseDto(BusAmenityMapping x) => new()
        {
            Id = x.Id,
            BusId = x.BusId,
            BusAmenityId = x.BusAmenityId,
        };
    }
}