// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.CompanyNetwork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    // The single unified "Dhaka to Chittagong" route every operator's OperatorRoute maps
    // onto (see AppDbContext's unique index on OriginTerminalId+DestinationTerminalId — only
    // one canonical route can exist per terminal pair). Read open to any logged-in user
    // (TripsController.Search and the operator-facing screens both need it), writes
    // Admin-only: this is shared platform routing data, not any one operator's to edit.
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class BusRoutesController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.BusRoutes.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.BusRoutes.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(BusRouteCreateDto dto)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = new BusRoute
            {
                OriginTerminalId = dto.OriginTerminalId,
                DestinationTerminalId = dto.DestinationTerminalId,
                ReverseRouteId = dto.ReverseRouteId,
                RouteCode = dto.RouteCode,
                Name = dto.Name,
                DistanceKm = dto.DistanceKm,
                EstimatedDurationMinutes = dto.EstimatedDurationMinutes,
                DefaultBaseFare = dto.DefaultBaseFare,
                IsActive = dto.IsActive,
            };

            db.BusRoutes.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, BusRouteUpdateDto dto)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = await db.BusRoutes.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "BusRoute not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This BusRoute was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.OriginTerminalId = dto.OriginTerminalId;
            item.DestinationTerminalId = dto.DestinationTerminalId;
            item.ReverseRouteId = dto.ReverseRouteId;
            item.RouteCode = dto.RouteCode;
            item.Name = dto.Name;
            item.DistanceKm = dto.DistanceKm;
            item.EstimatedDurationMinutes = dto.EstimatedDurationMinutes;
            item.DefaultBaseFare = dto.DefaultBaseFare;
            item.IsActive = dto.IsActive;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This BusRoute was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save BusRoute.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = await db.BusRoutes.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This BusRoute was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this BusRoute — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static BusRouteResponseDto ToResponseDto(BusRoute x) => new()
        {
            Id = x.Id,
            OriginTerminalId = x.OriginTerminalId,
            DestinationTerminalId = x.DestinationTerminalId,
            ReverseRouteId = x.ReverseRouteId,
            RouteCode = x.RouteCode,
            Name = x.Name,
            DistanceKm = x.DistanceKm,
            EstimatedDurationMinutes = x.EstimatedDurationMinutes,
            DefaultBaseFare = x.DefaultBaseFare,
            IsActive = x.IsActive,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}