// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.CompanyNetwork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    // Intermediate stops along a unified BusRoute. Same platform-wide-reference-data
    // reasoning as BusRoutesController: read open, writes Admin-only.
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class RouteStopsController(AppDbContext db) : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.RouteStops.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.RouteStops.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(RouteStopCreateDto dto)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = new RouteStop
            {
                BusRouteId = dto.BusRouteId,
                TerminalId = dto.TerminalId,
                StopOrder = dto.StopOrder,
                ArrivalOffsetMinutes = dto.ArrivalOffsetMinutes,
                DepartureOffsetMinutes = dto.DepartureOffsetMinutes,
                DistanceFromOriginKm = dto.DistanceFromOriginKm,
                IsPickupPoint = dto.IsPickupPoint,
                IsDropOffPoint = dto.IsDropOffPoint,
            };

            db.RouteStops.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, RouteStopUpdateDto dto)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = await db.RouteStops.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "RouteStop not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This RouteStop was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.BusRouteId = dto.BusRouteId;
            item.TerminalId = dto.TerminalId;
            item.StopOrder = dto.StopOrder;
            item.ArrivalOffsetMinutes = dto.ArrivalOffsetMinutes;
            item.DepartureOffsetMinutes = dto.DepartureOffsetMinutes;
            item.DistanceFromOriginKm = dto.DistanceFromOriginKm;
            item.IsPickupPoint = dto.IsPickupPoint;
            item.IsDropOffPoint = dto.IsDropOffPoint;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This RouteStop was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save RouteStop.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = await db.RouteStops.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This RouteStop was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this RouteStop — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static RouteStopResponseDto ToResponseDto(RouteStop x) => new()
        {
            Id = x.Id,
            BusRouteId = x.BusRouteId,
            TerminalId = x.TerminalId,
            StopOrder = x.StopOrder,
            ArrivalOffsetMinutes = x.ArrivalOffsetMinutes,
            DepartureOffsetMinutes = x.DepartureOffsetMinutes,
            DistanceFromOriginKm = x.DistanceFromOriginKm,
            IsPickupPoint = x.IsPickupPoint,
            IsDropOffPoint = x.IsDropOffPoint,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}