// <auto-generated>
// Simple CRUD controller — generated so this entity is reachable/testable from Swagger + Postman.
// </auto-generated>

using TicketPortal.Api.Data;
using TicketPortal.Api.DTO;
using TicketPortal.Api.Models.CompanyNetwork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace TicketPortal.Api.Controllers
{
    // Physical bus terminals ("Gabtoli", "Kalyanpur"...) — the origin/destination picker
    // behind TripsController.Search. Read is public (anyone visiting the site can search),
    // writes Admin-only: shared platform data, not any one operator's to rename or deactivate.
    [Authorize]
    [Route("api/[controller]")]
    [ApiController]
    public class TerminalsController(AppDbContext db) : ControllerBase
    {
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var items = await db.Terminals.ToListAsync();
            return Ok(items.Select(ToResponseDto));
        }

        [AllowAnonymous]
        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(Guid id)
        {
            var item = await db.Terminals.FirstOrDefaultAsync(x => x.Id == id);
            return item == null ? NotFound() : Ok(ToResponseDto(item));
        }

        [HttpPost]
        public async Task<IActionResult> Create(TerminalCreateDto dto)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = new Terminal
            {
                Name = dto.Name,
                Code = dto.Code,
                City = dto.City,
                District = dto.District,
                Division = dto.Division,
                Country = dto.Country,
                Address = dto.Address,
                Latitude = dto.Latitude,
                Longitude = dto.Longitude,
                IsActive = dto.IsActive,
            };

            db.Terminals.Add(item);
            await db.SaveChangesAsync();

            return CreatedAtAction(nameof(GetById), new { id = item.Id }, ToResponseDto(item));
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> Update(Guid id, TerminalUpdateDto dto)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = await db.Terminals.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound(new { message = "Terminal not found." });

            if (dto.RowVersion == null || dto.RowVersion.Length == 0)
                return BadRequest(new { message = "RowVersion is required." });

            if (!item.RowVersion.SequenceEqual(dto.RowVersion))
            {
                return Conflict(new
                {
                    message = "This Terminal was changed by another request. Please GET the latest data and try again."
                });
            }

            db.Entry(item).Property(x => x.RowVersion).OriginalValue = dto.RowVersion;

            item.Name = dto.Name;
            item.Code = dto.Code;
            item.City = dto.City;
            item.District = dto.District;
            item.Division = dto.Division;
            item.Country = dto.Country;
            item.Address = dto.Address;
            item.Latitude = dto.Latitude;
            item.Longitude = dto.Longitude;
            item.IsActive = dto.IsActive;
            item.UpdatedAtUtc = DateTime.UtcNow;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This Terminal was already modified or deleted by another request." });
            }
            catch (DbUpdateException ex)
            {
                var error = ex.InnerException?.InnerException?.Message ?? ex.InnerException?.Message ?? ex.Message;
                return Conflict(new { message = "Could not save Terminal.", details = error });
            }

            return Ok(ToResponseDto(item));
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (!User.IsInRole("Admin")) return Forbid();

            var item = await db.Terminals.FirstOrDefaultAsync(x => x.Id == id);
            if (item == null) return NotFound();

            // Soft delete — real business data is never hard-deleted (see AuditableEntity.MarkDeleted).
            item.MarkDeleted();

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Conflict(new { message = "This Terminal was already modified or deleted by another request." });
            }
            catch (DbUpdateException)
            {
                return Conflict(new { message = "Cannot delete this Terminal — it is still referenced by other records." });
            }

            return NoContent();
        }

        private static TerminalResponseDto ToResponseDto(Terminal x) => new()
        {
            Id = x.Id,
            Name = x.Name,
            Code = x.Code,
            City = x.City,
            District = x.District,
            Division = x.Division,
            Country = x.Country,
            Address = x.Address,
            Latitude = x.Latitude,
            Longitude = x.Longitude,
            IsActive = x.IsActive,
            CreatedAtUtc = x.CreatedAtUtc,
            UpdatedAtUtc = x.UpdatedAtUtc,
            RowVersion = x.RowVersion,
        };
    }
}