// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    // A customer (or staff, on their behalf) asks to cancel a booking or one ticket in it.
    // RequestedByUserId comes from the caller's own auth claim in the controller, never from
    // this body — and there's no Status/RequestedRefundAmount field here at all, because
    // CancellationProcessingService computes the refund amount from the trip's real
    // CancellationPolicy. The old generic CRUD let a client submit both of those directly,
    // i.e. approve their own refund amount in the same request that created it.
    public class CancellationRequestCreateDto
    {
        public Guid BookingId { get; set; }
        public Guid? TicketId { get; set; } // Null = cancel the whole booking, not just one ticket.

        [Required(AllowEmptyStrings = false)]
        [StringLength(250)]
        public string Reason { get; set; } = string.Empty;
    }

    // Staff review step. ApprovedRefundAmount is optional — omit it to accept the policy's own
    // calculated RequestedRefundAmount as-is, or set it to override (e.g. a goodwill exception).
    public class CancellationApproveDto
    {
        [Range(0, double.MaxValue, ErrorMessage = "ApprovedRefundAmount cannot be negative.")]
        public decimal? ApprovedRefundAmount { get; set; }

        [StringLength(500)]
        public string? Remarks { get; set; }
    }

    public class CancellationRejectDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(250)]
        public string RejectedReason { get; set; } = string.Empty;
    }

    // No CancellationRequestUpdateDto / raw PUT on purpose: a cancellation only ever moves
    // through CancellationProcessingService (Request -> Approve/Reject -> Complete) — see
    // CancellationRequestsController.

    public class CancellationRequestResponseDto
    {
        public Guid Id { get; set; }
        public Guid BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? RequestedByUserId { get; set; }
        public Guid? ApprovedByUserId { get; set; }
        public CancellationRequestStatus Status { get; set; } = CancellationRequestStatus.Requested;
        public string Reason { get; set; } = string.Empty;
        public string? RejectedReason { get; set; }
        // Breakdown behind RequestedRefundAmount — see CancellationRequest's own field
        // comments. Surfaced so the UI can show WHY the refund is less than what was paid
        // (tax/service charge are never refundable, and a policy fee may also apply) instead
        // of just the two numbers looking mismatched next to each other.
        public decimal BaseAmount { get; set; }
        public decimal BookingGrandTotalAtRequest { get; set; }
        public decimal? AppliedRefundPercentage { get; set; }
        public decimal? AppliedFixedCancellationFee { get; set; }
        public decimal RequestedRefundAmount { get; set; }
        public decimal? ApprovedRefundAmount { get; set; }
        // The Refund CancellationProcessingService.ApproveAsync creates (see that file's own
        // comment) — Approving a cancellation only ever creates this Refund at Requested; it
        // never advances it. Surfaced here so the admin console can link straight to
        // /admin/resource/Refunds/{RefundId} instead of an admin having to already know the
        // Refunds list even exists and search it for the right row. Null until the request has
        // actually been approved.
        public Guid? RefundId { get; set; }
        public string? RefundStatus { get; set; }
        public DateTime RequestedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime? ApprovedAtUtc { get; set; }
        public DateTime? CompletedAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // Everything about WHEN a hold starts/expires, its token, and its Status is decided by
    // SeatHoldService — never by the client. The client only says which seats it wants.
    public class SeatHoldCreateDto
    {
        public Guid TripId { get; set; }

        [MinLength(1, ErrorMessage = "At least one seat must be selected.")]
        public List<Guid> TripSeatIds { get; set; } = new();
    }

    // No SeatHoldUpdateDto / raw PUT on purpose: a hold's Status only ever moves through
    // SeatHoldService (Create → hold, Release, or the expiry sweep) — see SeatHoldsController.

    public class SeatHoldResponseDto
    {
        public Guid Id { get; set; }
        public Guid TripId { get; set; }
        public Guid? HeldByUserId { get; set; }
        public string HoldToken { get; set; } = string.Empty;
        public DateTime HoldStartedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime HoldExpiresAtUtc { get; set; }
        public SeatHoldStatus Status { get; set; } = SeatHoldStatus.Active;

        // Convenience for the front-end's countdown timer — 0 once the hold is no longer Active.
        public int SecondsRemaining { get; set; }

        public string? ClientIpAddress { get; set; }
        public string? UserAgent { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO for SeatHoldItem: items are written only as a side effect of
    // SeatHoldService.HoldSeatsAsync. SeatHoldItemsController is read-only.
    public class SeatHoldItemResponseDto
    {
        public Guid Id { get; set; }
        public Guid SeatHoldId { get; set; }
        public Guid TripSeatId { get; set; }
        public decimal FareAtHold { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO for Ticket: tickets are issued only by PaymentConfirmationService
    // the moment an online payment is confirmed. TicketsController is read-only.
    // =========================================================
    // Ticket Response — includes related booking/trip/bus/passenger info
    // =========================================================
    public class TicketResponseDto
    {
        // ============ TICKET ============
        public Guid Id { get; set; }
        public string TicketNumber { get; set; } = string.Empty;
        public string? ExternalTicketKey { get; set; }
        public decimal Fare { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal FinalFare { get; set; }
        public TicketStatus Status { get; set; } = TicketStatus.PendingPayment;
        public string? QrCodePayload { get; set; }

        // ============ ⭐ BOOKING ============
        public Guid BookingId { get; set; }
        public string? Pnr { get; set; }

        // ============ ⭐ PASSENGER ============
        public Guid BookingPassengerId { get; set; }
        public string? PassengerName { get; set; }
        public string? PassengerPhone { get; set; }
        public Gender? PassengerGender { get; set; }
        public int? PassengerAge { get; set; }

        // ============ ⭐ SEAT ============
        public Guid TripSeatId { get; set; }
        public string SeatNumberSnapshot { get; set; } = string.Empty;
        public string? SeatNumber { get; set; }

        // ============ ⭐ TRIP ============
        public Guid TripId { get; set; }
        public string? TripCode { get; set; }
        public DateTime? DepartureTimeUtc { get; set; }
        public DateTime? ArrivalTimeUtc { get; set; }

        // ============ ⭐ BUS ============
        public Guid? BusId { get; set; }
        public string? BusName { get; set; }
        public string? BusBrand { get; set; }
        public string? BusModel { get; set; }
        public string? BusCoachNumber { get; set; }
        public string? BusRegistrationNumber { get; set; }
        public bool BusHasWifi { get; set; }
        public bool BusHasToilet { get; set; }

        // ============ ⭐ OPERATOR ============
        public Guid? BusOperatorId { get; set; }
        public string? BusOperatorName { get; set; }

        // ============ ⭐ TERMINALS ============
        public Guid? DepartureTerminalId { get; set; }
        public string? DepartureTerminalName { get; set; }
        public string? DepartureCity { get; set; }
        public Guid? ArrivalTerminalId { get; set; }
        public string? ArrivalTerminalName { get; set; }
        public string? ArrivalCity { get; set; }

        // ============ BOARDING / DROPPING ============
        public string? BoardingTerminalName { get; set; }
        public string? DroppingTerminalName { get; set; }

        // ============ TIMESTAMPS ============
        public DateTime? IssuedAtUtc { get; set; }
        public DateTime? CheckedInAtUtc { get; set; }
        public DateTime? CancelledAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }

        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}
