// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class BusAmenityCreateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string Name { get; set; } = string.Empty;

        [StringLength(200)]
        public string? IconUrl { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class BusAmenityUpdateDto : BusAmenityCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class BusAmenityResponseDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string? IconUrl { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class BusAmenityMappingCreateDto
    {
        public Guid BusId { get; set; }
        public Guid BusAmenityId { get; set; }
    }

    public class BusAmenityMappingUpdateDto : BusAmenityMappingCreateDto
    {
    }

    public class BusAmenityMappingResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusId { get; set; }
        public Guid BusAmenityId { get; set; }
    }

    public class BusCategoryCreateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string Name { get; set; } = string.Empty;

        [StringLength(250)]
        public string? Description { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class BusCategoryUpdateDto : BusCategoryCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class BusCategoryResponseDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string? Description { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class BusImageCreateDto
    {
        public Guid BusId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(300)]
        public string ImageUrl { get; set; } = string.Empty;

        [StringLength(120)]
        public string? Caption { get; set; }
        public bool IsPrimary { get; set; }

        [Range(0, int.MaxValue)]
        public int DisplayOrder { get; set; }
    }

    public class BusImageUpdateDto : BusImageCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class BusImageResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusId { get; set; }
        public string ImageUrl { get; set; } = string.Empty;
        public string? Caption { get; set; }
        public bool IsPrimary { get; set; }
        public int DisplayOrder { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class BusMaintenanceLogCreateDto
    {
        public Guid BusId { get; set; }
        public DateTime MaintenanceDateUtc { get; set; }

        [Range(0, int.MaxValue)]
        public int? OdometerKm { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string Title { get; set; } = string.Empty;

        [StringLength(1000)]
        public string? Description { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "Cost cannot be negative.")]
        public decimal Cost { get; set; }
        public DateTime? NextDueDateUtc { get; set; }

        [StringLength(120)]
        public string? PerformedBy { get; set; }
    }

    public class BusMaintenanceLogUpdateDto : BusMaintenanceLogCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class BusMaintenanceLogResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusId { get; set; }
        public DateTime MaintenanceDateUtc { get; set; }
        public int? OdometerKm { get; set; }
        public string Title { get; set; } = string.Empty;
        public string? Description { get; set; }
        public decimal Cost { get; set; }
        public DateTime? NextDueDateUtc { get; set; }
        public string? PerformedBy { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}