// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class LanguageCreateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(10)]
        public string Code { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string Name { get; set; } = string.Empty;
        public bool IsDefault { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class LanguageUpdateDto : LanguageCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class LanguageResponseDto
    {
        public Guid Id { get; set; }
        public string Code { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public bool IsDefault { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SystemSettingCreateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string Key { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(2000)]
        public string Value { get; set; } = string.Empty;

        [StringLength(250)]
        public string? Description { get; set; }
    }

    public class SystemSettingUpdateDto : SystemSettingCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SystemSettingResponseDto
    {
        public Guid Id { get; set; }
        public string Key { get; set; } = string.Empty;
        public string Value { get; set; } = string.Empty;
        public string? Description { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}