// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    // No Create/Update DTO: a trail table is never client-writable. ActivityLogsController is
    // read-only, Admin/Staff-only.
    public class ActivityLogResponseDto
    {
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public string Action { get; set; } = string.Empty;
        public string? EntityName { get; set; }
        public string? EntityId { get; set; }
        public string? IpAddress { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO: a trail table is never client-writable. AuditLogsController is
    // read-only, Admin/Staff-only.
    public class AuditLogResponseDto
    {
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }

        // Completion Plan v2, Chunk 9 task 4 ("readable audit/login-history page — actor name
        // instead of raw user id — join on the server"). Resolved by AuditLogsController from
        // ApplicationUser, not stored on AuditLog itself. Both null when UserId is null (a
        // system/background-job action) or when the account has since been deleted.
        public string? ActorUserName { get; set; }
        public string? ActorFullName { get; set; }

        public string EntityName { get; set; } = string.Empty;
        public string EntityId { get; set; } = string.Empty;
        public string Action { get; set; } = string.Empty;
        public string? OldValuesJson { get; set; }
        public string? NewValuesJson { get; set; }
        public string? IpAddress { get; set; }
        public string? UserAgent { get; set; }
        public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    }

    // No Create/Update DTO: a trail table is never client-writable. Written only by
    // AccountController.Login on every attempt (success or failure). LoginHistoriesController
    // is read-only.
    public class LoginHistoryResponseDto
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }

        // Same server-side join as AuditLogResponseDto above — see that field's comment.
        // LoginHistory.UserId is never null (unlike AuditLog's), but the account can still have
        // been deleted since, so these stay nullable.
        public string? ActorUserName { get; set; }
        public string? ActorFullName { get; set; }

        public DateTime LoginAtUtc { get; set; } = DateTime.UtcNow;
        public string? IpAddress { get; set; }
        public string? UserAgent { get; set; }
        public bool Success { get; set; }
    }

    // No Create/Update DTO: a trail table is never client-writable. Nothing sends real
    // notifications yet (no email/SMS provider is wired in), so nothing writes here yet either
    // — NotificationLogsController is read-only in the meantime.
    public class NotificationLogResponseDto
    {
        public Guid Id { get; set; }
        public Guid? BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? UserId { get; set; }
        public NotificationChannel Channel { get; set; }
        public string Recipient { get; set; } = string.Empty;
        public string? Subject { get; set; }
        public string Message { get; set; } = string.Empty;
        public NotificationStatus Status { get; set; } = NotificationStatus.Queued;
        public string? ProviderMessageId { get; set; }
        public string? ErrorMessage { get; set; }
        public DateTime? SentAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}