// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class CommissionRuleCreateDto
    {
        public Guid BusOperatorId { get; set; }
        public Guid? OperatorContractId { get; set; }
        public Guid? BusRouteId { get; set; }
        public SaleChannel SaleChannel { get; set; }
        public CommissionType CommissionType { get; set; } = CommissionType.Percentage;

        // Non-negative regardless of CommissionType — a Percentage value is additionally capped
        // at 100 in CommissionRulesController, since whether 100 is a valid ceiling depends on
        // which type this is (a flat CommissionValue has no such ceiling).
        [Range(0, double.MaxValue, ErrorMessage = "CommissionValue cannot be negative.")]
        public decimal CommissionValue { get; set; }
        public DateOnly EffectiveFrom { get; set; }
        public DateOnly? EffectiveTo { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class CommissionRuleUpdateDto : CommissionRuleCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CommissionRuleResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public Guid? OperatorContractId { get; set; }
        public Guid? BusRouteId { get; set; }
        public SaleChannel SaleChannel { get; set; }
        public CommissionType CommissionType { get; set; } = CommissionType.Percentage;
        public decimal CommissionValue { get; set; }
        public DateOnly EffectiveFrom { get; set; }
        public DateOnly? EffectiveTo { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorContractCreateDto
    {
        public Guid BusOperatorId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(60)]
        public string ContractNo { get; set; } = string.Empty;
        public DateOnly EffectiveFrom { get; set; }
        public DateOnly? EffectiveTo { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "SettlementIntervalDays must be at least 1.")]
        public int SettlementIntervalDays { get; set; } = 7;
        public GatewayFeeBearer GatewayFeeBearer { get; set; } = GatewayFeeBearer.Operator;
        public bool IsActive { get; set; } = true;

        [StringLength(500)]
        public string? Notes { get; set; }
    }

    public class OperatorContractUpdateDto : OperatorContractCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorContractResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public string ContractNo { get; set; } = string.Empty;
        public DateOnly EffectiveFrom { get; set; }
        public DateOnly? EffectiveTo { get; set; }
        public int SettlementIntervalDays { get; set; } = 7;
        public GatewayFeeBearer GatewayFeeBearer { get; set; } = GatewayFeeBearer.Operator;
        public bool IsActive { get; set; } = true;
        public string? Notes { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // --- Piece 3: Settlement, Invoicing & Payouts ---
    // Every write in this domain now goes through a service (SettlementGenerationService,
    // PayoutProcessingService, InvoicePaymentService) instead of a generic PUT — see those
    // classes for why. Status, computed totals, and generated numbers (SettlementNo/StatementNo/
    // InvoiceNo/PayoutNo) are never client-settable; they're system-assigned or derived from real
    // events (receipts received, ledger rows swept up), matching the "DTOs never expose a
    // client-settable Status/computed total" convention used throughout this codebase.

    public class OperatorInvoiceCreateDto
    {
        public Guid BusOperatorId { get; set; }
        public Guid? OperatorStatementId { get; set; }
        public DateOnly InvoiceDate { get; set; }
        public DateOnly? DueDate { get; set; }
        public SettlementDirection Direction { get; set; }

        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than zero.")]
        public decimal Amount { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(3, MinimumLength = 3)]
        public string Currency { get; set; } = "BDT";
    }

    public class OperatorInvoiceActionDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(500)]
        public string Reason { get; set; } = string.Empty;
    }

    public class OperatorInvoiceResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public Guid? OperatorStatementId { get; set; }
        public string InvoiceNo { get; set; } = string.Empty;
        public DateOnly InvoiceDate { get; set; }
        public DateOnly? DueDate { get; set; }
        public SettlementDirection Direction { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; } = "BDT";
        public InvoiceStatus Status { get; set; } = InvoiceStatus.Draft;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorPaymentReceiptCreateDto
    {
        public Guid OperatorInvoiceId { get; set; }

        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than zero.")]
        public decimal Amount { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(3, MinimumLength = 3)]
        public string Currency { get; set; } = "BDT";

        [StringLength(120)]
        public string? ReferenceNo { get; set; }

        [StringLength(250)]
        public string? Notes { get; set; }
    }

    public class OperatorPaymentReceiptResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorInvoiceId { get; set; }
        public DateTime ReceivedAtUtc { get; set; } = DateTime.UtcNow;
        public decimal Amount { get; set; }
        public string Currency { get; set; } = "BDT";
        public string? ReferenceNo { get; set; }
        public string? Notes { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorPayoutCreateDto
    {
        public Guid BusOperatorId { get; set; }
        public Guid? OperatorSettlementId { get; set; }

        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than zero.")]
        public decimal Amount { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(3, MinimumLength = 3)]
        public string Currency { get; set; } = "BDT";

        [StringLength(250)]
        public string? Notes { get; set; }
    }

    public class OperatorPayoutCompleteDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string BankTransactionReference { get; set; } = string.Empty;
    }

    public class OperatorPayoutActionDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(500)]
        public string Reason { get; set; } = string.Empty;
    }

    public class OperatorPayoutResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public Guid? OperatorSettlementId { get; set; }
        public string PayoutNo { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Currency { get; set; } = "BDT";
        public PayoutStatus Status { get; set; } = PayoutStatus.Pending;
        public DateTime? PaidAtUtc { get; set; }
        public string? BankTransactionReference { get; set; }
        public string? Notes { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // Drives SettlementGenerationService.GenerateSettlementAsync — the "run settlement for this
    // operator and date range" action that replaces raw OperatorSettlement CRUD entirely.
    public class SettlementGenerateDto
    {
        public Guid BusOperatorId { get; set; }
        public DateOnly FromDate { get; set; }
        public DateOnly ToDate { get; set; }

        [StringLength(500)]
        public string? Remarks { get; set; }
    }

    public class SettlementApproveDto
    {
        [StringLength(500)]
        public string? Remarks { get; set; }
    }

    public class OperatorSettlementResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public Guid? OperatorStatementId { get; set; }
        public Guid? OperatorInvoiceId { get; set; }
        public string SettlementNo { get; set; } = string.Empty;
        public DateOnly FromDate { get; set; }
        public DateOnly ToDate { get; set; }
        public SettlementDirection Direction { get; set; } = SettlementDirection.PlatformPaysOperator;
        public SettlementStatus Status { get; set; } = SettlementStatus.Draft;
        public decimal OnlineGrossAmount { get; set; }
        public decimal OfflineGrossAmount { get; set; }
        public decimal PlatformCharge { get; set; }
        public decimal GatewayCharge { get; set; }
        public decimal RefundAmount { get; set; }
        public decimal NetAmount { get; set; }
        public DateTime? PaidAtUtc { get; set; }
        public string? Remarks { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // GetById returns this richer shape — the line-by-line breakdown behind the settlement's
    // headline totals, for a single request instead of a second round trip to
    // OperatorSettlementItemsController.
    public class OperatorSettlementDetailResponseDto : OperatorSettlementResponseDto
    {
        public List<OperatorSettlementItemResponseDto> Items { get; set; } = new();
    }

    // No Create/Update DTO: every row is written by SettlementGenerationService as part of
    // generating its parent settlement. OperatorSettlementItemsController is read-only.
    public class OperatorSettlementItemResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorSettlementId { get; set; }
        public Guid? BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? PlatformLedgerId { get; set; }
        public StatementItemType ItemType { get; set; }
        public SaleChannel SaleChannel { get; set; }
        public decimal TicketFare { get; set; }
        public decimal PlatformCharge { get; set; }
        public decimal GatewayCharge { get; set; }
        public decimal RefundAmount { get; set; }
        public decimal NetAmount { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO: an OperatorStatement is generated alongside its settlement by
    // SettlementGenerationService, never created by hand. OperatorStatementsController is
    // read-only — see the design note at the top of SettlementGenerationService.cs.
    public class OperatorStatementResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public string StatementNo { get; set; } = string.Empty;
        public DateOnly FromDate { get; set; }
        public DateOnly ToDate { get; set; }
        public decimal PlatformPayableToOperator { get; set; }
        public decimal OperatorPayableToPlatform { get; set; }
        public decimal NetAmount { get; set; }
        public SettlementDirection NetDirection { get; set; } = SettlementDirection.PlatformPaysOperator;
        public SettlementStatus Status { get; set; } = SettlementStatus.Draft;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorStatementDetailResponseDto : OperatorStatementResponseDto
    {
        public List<OperatorStatementItemResponseDto> Items { get; set; } = new();
    }

    // No Create/Update DTO: written only by SettlementGenerationService, one row per ledger
    // entry swept into the parent statement. OperatorStatementItemsController is read-only.
    public class OperatorStatementItemResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorStatementId { get; set; }
        public Guid? BookingId { get; set; }
        public Guid? TicketId { get; set; }
        public Guid? PaymentId { get; set; }
        public Guid? RefundId { get; set; }
        public Guid? PlatformLedgerId { get; set; }
        public StatementItemType ItemType { get; set; }
        public SaleChannel SaleChannel { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public string Currency { get; set; } = "BDT";
        public string? Description { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO for OperatorWallet: FinanceLedgerService is the only writer.
    // OperatorWalletsController is read-only.
    public class OperatorWalletResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public decimal TotalOnlineSalesAmount { get; set; }
        public decimal TotalCounterSalesAmount { get; set; }
        public decimal PendingSettlementBalance { get; set; }
        public decimal AvailablePayoutBalance { get; set; }
        public decimal WithdrawnAmount { get; set; }
        public decimal TotalPlatformCommission { get; set; }
        public decimal TotalGatewayCharge { get; set; }
        public decimal OperatorReceivableFromPlatform { get; set; }
        public decimal PlatformReceivableFromOperator { get; set; }
        public DateTime? LastStatementDateUtc { get; set; }
        public DateTime? LastSettlementDateUtc { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO for PlatformLedger: it's an append-only diary, and
    // FinanceLedgerService is the only writer. PlatformLedgersController is read-only.
    public class PlatformLedgerResponseDto
    {
        public Guid Id { get; set; }
        public Guid? BookingId { get; set; }
        public Guid? PaymentId { get; set; }
        public Guid? RefundId { get; set; }
        public Guid? BusOperatorId { get; set; }
        public Guid? OperatorSettlementId { get; set; }
        public string LedgerNo { get; set; } = string.Empty;
        public StatementItemType ItemType { get; set; }
        public SaleChannel? SaleChannel { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public string Currency { get; set; } = "BDT";
        public string? ReferenceNo { get; set; }
        public string? Description { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}