// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class ExternalBookingMappingCreateDto
    {
        public Guid OperatorIntegrationId { get; set; }
        public Guid BookingId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string ExternalBookingKey { get; set; } = string.Empty;

        [StringLength(120)]
        public string? ExternalPnr { get; set; }
        public BookingStatus? LastKnownExternalStatus { get; set; }
        public DateTime? LastSyncedAtUtc { get; set; }
    }

    public class ExternalBookingMappingUpdateDto : ExternalBookingMappingCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class ExternalBookingMappingResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorIntegrationId { get; set; }
        public Guid BookingId { get; set; }
        public string ExternalBookingKey { get; set; } = string.Empty;
        public string? ExternalPnr { get; set; }
        public BookingStatus? LastKnownExternalStatus { get; set; }
        public DateTime? LastSyncedAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class ExternalRouteMappingCreateDto
    {
        public Guid OperatorIntegrationId { get; set; }
        public Guid OperatorRouteId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string ExternalRouteKey { get; set; } = string.Empty;

        [StringLength(160)]
        public string? ExternalRouteName { get; set; }
    }

    public class ExternalRouteMappingUpdateDto : ExternalRouteMappingCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class ExternalRouteMappingResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorIntegrationId { get; set; }
        public Guid OperatorRouteId { get; set; }
        public string ExternalRouteKey { get; set; } = string.Empty;
        public string? ExternalRouteName { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class ExternalSeatMappingCreateDto
    {
        public Guid OperatorIntegrationId { get; set; }
        public Guid TripSeatId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string ExternalSeatKey { get; set; } = string.Empty;

        [StringLength(20)]
        public string? ExternalSeatNumber { get; set; }
    }

    public class ExternalSeatMappingUpdateDto : ExternalSeatMappingCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class ExternalSeatMappingResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorIntegrationId { get; set; }
        public Guid TripSeatId { get; set; }
        public string ExternalSeatKey { get; set; } = string.Empty;
        public string? ExternalSeatNumber { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class ExternalTripMappingCreateDto
    {
        public Guid OperatorIntegrationId { get; set; }
        public Guid TripId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string ExternalTripKey { get; set; } = string.Empty;
        public DateTime? LastSyncedAtUtc { get; set; }
        public string? LastSeatSnapshotJson { get; set; }
    }

    public class ExternalTripMappingUpdateDto : ExternalTripMappingCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class ExternalTripMappingResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorIntegrationId { get; set; }
        public Guid TripId { get; set; }
        public string ExternalTripKey { get; set; } = string.Empty;
        public DateTime? LastSyncedAtUtc { get; set; }
        public string? LastSeatSnapshotJson { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO: this will be written by the future ERP sync worker (flagged as
    // follow-up work, not built here), never by a client directly. IntegrationSyncLogsController
    // is read-only, Admin/Staff-only.
    public class IntegrationSyncLogResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorIntegrationId { get; set; }
        public string EntityName { get; set; } = string.Empty;
        public string? EntityKey { get; set; }
        public string Operation { get; set; } = string.Empty;
        public IntegrationSyncStatus Status { get; set; } = IntegrationSyncStatus.Pending;
        public DateTime StartedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime? CompletedAtUtc { get; set; }
        public string? RequestJson { get; set; }
        public string? ResponseJson { get; set; }
        public string? ErrorMessage { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO: same reasoning as IntegrationSyncLog above — written by the future
    // ERP sync worker, never by a client. IntegrationWebhookLogsController is read-only,
    // Admin/Staff-only.
    public class IntegrationWebhookLogResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorIntegrationId { get; set; }
        public string? ExternalEventId { get; set; }
        public string EventType { get; set; } = string.Empty;
        public DateTime ReceivedAtUtc { get; set; } = DateTime.UtcNow;
        public bool IsProcessed { get; set; }
        public DateTime? ProcessedAtUtc { get; set; }
        public string? PayloadJson { get; set; }
        public string? ErrorMessage { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorIntegrationCreateDto
    {
        public Guid BusOperatorId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string Name { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(300)]
        [Url(ErrorMessage = "BaseUrl must be a valid URL.")]
        public string BaseUrl { get; set; } = string.Empty;
        public IntegrationAuthType AuthType { get; set; } = IntegrationAuthType.ApiKey;

        [StringLength(120)]
        public string? ApiKeyHeaderName { get; set; }

        [StringLength(1000)]
        public string? SecretReference { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "TimeoutSeconds must be at least 1.")]
        public int TimeoutSeconds { get; set; } = 30;
        public bool IsActive { get; set; } = true;
        public DateTime? LastSuccessfulSyncAtUtc { get; set; }
    }

    public class OperatorIntegrationUpdateDto : OperatorIntegrationCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // Chunk 8 task 3: this is the read shape returned to the browser, and it deliberately does
    // NOT include the raw SecretReference — only whether one is set (HasSecret) and a masked
    // preview safe to display (e.g. "env:HAN••••_KEY"). The real secret value is never returned
    // by any endpoint; see ExternalBookingSyncService.ResolveSecret for where it's actually
    // read from (server-side only, at call time). Write it via OperatorIntegrationCreateDto/
    // OperatorIntegrationUpdateDto instead, which stay write-only for this field.
    public class OperatorIntegrationResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string BaseUrl { get; set; } = string.Empty;
        public IntegrationAuthType AuthType { get; set; } = IntegrationAuthType.ApiKey;
        public string? ApiKeyHeaderName { get; set; }
        public bool HasSecret { get; set; }
        public string? SecretReferenceMasked { get; set; }
        public int TimeoutSeconds { get; set; } = 30;
        public bool IsActive { get; set; } = true;
        public DateTime? LastSuccessfulSyncAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // Chunk 8 / RBAC Amendment v3 §8: the redacted view an operator manager can see for their
    // OWN operator's integration (Permissions.IntegrationsRead) — mode, health, recent activity,
    // nothing else. No BaseUrl, no auth details, no secret (masked or otherwise), no sync-log
    // detail. Full records (OperatorIntegrationResponseDto, IntegrationSyncLogResponseDto,
    // mapping tables) stay behind Permissions.IntegrationsManage (Admin-only) — see
    // OperatorIntegrationsController.GetStatus vs. the rest of that controller.
    public class OperatorIntegrationStatusDto
    {
        public Guid BusOperatorId { get; set; }
        public string BusOperatorName { get; set; } = string.Empty;
        public OperatorInventoryMode InventoryMode { get; set; }
        public bool HasIntegrationConfigured { get; set; }
        public string? IntegrationName { get; set; }
        public bool IsActive { get; set; }
        public DateTime? LastSuccessfulSyncAtUtc { get; set; }
        public string? LastSyncStatus { get; set; }
        public DateTime? LastSyncAtUtc { get; set; }
        public int RecentFailureCount { get; set; } // Failed sync-log rows in the last 24h.
    }

    public class OperatorIntegrationEndpointCreateDto
    {
        public Guid OperatorIntegrationId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string Purpose { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(10)]
        public string HttpMethod { get; set; } = "GET";

        [Required(AllowEmptyStrings = false)]
        [StringLength(300)]
        public string PathTemplate { get; set; } = string.Empty;
        public bool IsActive { get; set; } = true;
    }

    public class OperatorIntegrationEndpointUpdateDto : OperatorIntegrationEndpointCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class OperatorIntegrationEndpointResponseDto
    {
        public Guid Id { get; set; }
        public Guid OperatorIntegrationId { get; set; }
        public string Purpose { get; set; } = string.Empty;
        public string HttpMethod { get; set; } = "GET";
        public string PathTemplate { get; set; } = string.Empty;
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}