// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class CurrencyCreateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(3, MinimumLength = 3)]
        public string Code { get; set; } = "BDT";

        [Required(AllowEmptyStrings = false)]
        [StringLength(10)]
        public string Symbol { get; set; } = string.Empty;

        [Range(0.000001, double.MaxValue, ErrorMessage = "ExchangeRateToBase must be greater than zero.")]
        public decimal ExchangeRateToBase { get; set; } = 1m;
        public bool IsBaseCurrency { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class CurrencyUpdateDto : CurrencyCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CurrencyResponseDto
    {
        public Guid Id { get; set; }
        public string Code { get; set; } = "BDT";
        public string Symbol { get; set; } = string.Empty;
        public decimal ExchangeRateToBase { get; set; } = 1m;
        public bool IsBaseCurrency { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class FareRuleCreateDto
    {
        public Guid? BusOperatorId { get; set; }
        public Guid BusRouteId { get; set; }
        public BusType? BusType { get; set; }
        public SeatType? SeatType { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "BaseFare cannot be negative.")]
        public decimal BaseFare { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(3, MinimumLength = 3)]
        public string Currency { get; set; } = "BDT";
        public DateTime EffectiveFromUtc { get; set; }
        public DateTime? EffectiveToUtc { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class FareRuleUpdateDto : FareRuleCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class FareRuleResponseDto
    {
        public Guid Id { get; set; }
        public Guid? BusOperatorId { get; set; }
        public Guid BusRouteId { get; set; }
        public BusType? BusType { get; set; }
        public SeatType? SeatType { get; set; }
        public decimal BaseFare { get; set; }
        public string Currency { get; set; } = "BDT";
        public DateTime EffectiveFromUtc { get; set; }
        public DateTime? EffectiveToUtc { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // Step 3 of checkout: start a payment attempt. Amount/Currency/CollectedBy/Status are never
    // taken from the client — PaymentConfirmationService fills those in from the booking itself.
    public class PaymentInitiateDto
    {
        public Guid BookingId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(100)]
        public string HoldToken { get; set; } = string.Empty;
        public PaymentMethod Method { get; set; }
        public Guid? PaymentProviderId { get; set; }
    }

    // Step 4: what the payment gateway reports back once it's done. Note there's no Status
    // field here on purpose — which endpoint you call (Confirm vs Fail) is what decides the
    // outcome, so it can't be spoofed by just sending a different Status value.
    // TODO: once a real gateway is wired in, this is where its callback signature gets verified
    // before any of this is trusted.
    public class PaymentGatewayResultDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(100)]
        public string HoldToken { get; set; } = string.Empty;

        [StringLength(100)]
        public string? GatewayTransactionId { get; set; }

        // Chunk 4 P0 task 3: kept for shape-compatibility with what a real gateway callback would
        // eventually send, but PaymentConfirmationService.ConfirmOnlinePaymentAsync no longer
        // trusts this value for the ledger — it recomputes the real fee server-side from
        // PaymentMethodConfiguration instead. Do not wire this back into the ledger without the
        // same signature verification the TODO above already calls for.
        [Range(0, double.MaxValue, ErrorMessage = "GatewayFeeAmount cannot be negative.")]
        public decimal GatewayFeeAmount { get; set; }

        [StringLength(2000)]
        public string? GatewayResponseJson { get; set; }
    }

    public class PaymentFailDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(100)]
        public string HoldToken { get; set; } = string.Empty;

        [StringLength(500)]
        public string? Reason { get; set; }
    }

    // Counter-sale equivalent of Initiate+Confirm combined into one call: cash changes hands
    // in person at the moment this is submitted, so there's no separate gateway round trip to
    // wait on. Only valid against a Booking created with SalesCounterId set (SaleChannel ==
    // Counter) — see PaymentConfirmationService.ConfirmCounterSaleAsync.
    public class CounterSaleConfirmDto
    {
        public Guid BookingId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(100)]
        public string HoldToken { get; set; } = string.Empty;
        public PaymentMethod Method { get; set; } = PaymentMethod.Cash;
    }

    public class PaymentResponseDto
    {
        public Guid Id { get; set; }
        public Guid BookingId { get; set; }
        public Guid? PaymentProviderId { get; set; }
        public PaymentMethod Method { get; set; }
        public PaymentGateway Gateway { get; set; } = PaymentGateway.None;
        public MoneyCollectedBy CollectedBy { get; set; } = MoneyCollectedBy.Platform;
        public string? GatewayTransactionId { get; set; }
        public string? MerchantInvoiceNumber { get; set; }
        public decimal Amount { get; set; }
        public decimal GatewayFeeAmount { get; set; }
        public decimal NetReceivedAmount { get; set; }
        public string Currency { get; set; } = "BDT";
        public PaymentStatus Status { get; set; } = PaymentStatus.Initiated;
        public DateTime TransactionDateUtc { get; set; } = DateTime.UtcNow;
        public DateTime? PaidAtUtc { get; set; }
        public DateTime? FailedAtUtc { get; set; }
        public string? GatewayResponseJson { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO: this is the append-only trail of a Payment's own status changes,
    // written exclusively by PaymentConfirmationService. PaymentHistoriesController is
    // read-only.
    public class PaymentHistoryResponseDto
    {
        public Guid Id { get; set; }
        public Guid PaymentId { get; set; }
        public PaymentStatus Status { get; set; }
        public DateTime ChangedAtUtc { get; set; } = DateTime.UtcNow;
        public string? Remarks { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class PaymentMethodConfigurationCreateDto
    {
        public Guid PaymentProviderId { get; set; }
        public PaymentMethod Method { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string DisplayName { get; set; } = string.Empty;

        [Range(0, double.MaxValue, ErrorMessage = "FixedFee cannot be negative.")]
        public decimal? FixedFee { get; set; }

        [Range(0, 100, ErrorMessage = "PercentageFee must be between 0 and 100.")]
        public decimal? PercentageFee { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class PaymentMethodConfigurationUpdateDto : PaymentMethodConfigurationCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class PaymentMethodConfigurationResponseDto
    {
        public Guid Id { get; set; }
        public Guid PaymentProviderId { get; set; }
        public PaymentMethod Method { get; set; }
        public string DisplayName { get; set; } = string.Empty;
        public decimal? FixedFee { get; set; }
        public decimal? PercentageFee { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class PaymentProviderCreateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string Name { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(40)]
        public string Code { get; set; } = string.Empty;
        public PaymentProviderKind ProviderKind { get; set; } = PaymentProviderKind.Gateway;
        public PaymentGateway Gateway { get; set; } = PaymentGateway.None;

        [StringLength(300)]
        [Url(ErrorMessage = "CheckoutBaseUrl must be a valid URL.")]
        public string? CheckoutBaseUrl { get; set; }

        [StringLength(300)]
        [Url(ErrorMessage = "WebhookUrl must be a valid URL.")]
        public string? WebhookUrl { get; set; }
        public bool SupportsRefund { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class PaymentProviderUpdateDto : PaymentProviderCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class PaymentProviderResponseDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Code { get; set; } = string.Empty;
        public PaymentProviderKind ProviderKind { get; set; } = PaymentProviderKind.Gateway;
        public PaymentGateway Gateway { get; set; } = PaymentGateway.None;
        public string? CheckoutBaseUrl { get; set; }
        public string? WebhookUrl { get; set; }
        public bool SupportsRefund { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO: raw inbound gateway webhook data has no legitimate client-facing
    // write path. Nothing writes here yet either, since no real payment gateway is wired in —
    // that lands with the actual webhook receiver endpoint. PaymentWebhookEventsController is
    // read-only, Admin/Staff-only in the meantime.
    public class PaymentWebhookEventResponseDto
    {
        public Guid Id { get; set; }
        public Guid? PaymentId { get; set; }
        public Guid? PaymentProviderId { get; set; }
        public string ProviderEventId { get; set; } = string.Empty;
        public string EventType { get; set; } = string.Empty;
        public PaymentStatus? ReportedStatus { get; set; }
        public DateTime ReceivedAtUtc { get; set; } = DateTime.UtcNow;
        public bool IsProcessed { get; set; }
        public DateTime? ProcessedAtUtc { get; set; }
        public string? PayloadJson { get; set; }
        public string? ErrorMessage { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No RefundCreateDto: a Refund is only ever created automatically (by
    // PaymentConfirmationService today, CancellationRequest handling later) — never directly
    // by a client. From there it only moves via these two actions, or Process (no body needed).
    public class RefundApproveDto
    {
        [StringLength(500)]
        public string? Remarks { get; set; }
    }

    public class RefundRejectDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(250)]
        public string Reason { get; set; } = string.Empty;
    }

    // Used only to complete a guest refund that's sitting at PendingManualPayout — staff
    // supplies proof (bank/mobile-banking reference) that the guest was actually paid back.
    public class RefundManualPayoutDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(100)]
        public string ManualPayoutReference { get; set; } = string.Empty;
    }

    public class RefundResponseDto
    {
        public Guid Id { get; set; }
        public Guid BookingId { get; set; }
        public Guid PaymentId { get; set; }
        public Guid? CancellationRequestId { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; } = "BDT";
        public RefundStatus Status { get; set; } = RefundStatus.Requested;
        public string Reason { get; set; } = string.Empty;
        public string? GatewayRefundReference { get; set; }
        public string? ManualPayoutReference { get; set; }
        public DateTime RequestedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime? RefundedAtUtc { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO for RefundHistory either: it's written only by
    // RefundProcessingService. RefundHistoriesController is read-only.
    public class RefundHistoryResponseDto
    {
        public Guid Id { get; set; }
        public Guid RefundId { get; set; }
        public RefundStatus Status { get; set; }
        public DateTime ChangedAtUtc { get; set; } = DateTime.UtcNow;
        public string? Remarks { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class TaxRuleCreateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string Name { get; set; } = string.Empty;

        [Range(0, 100, ErrorMessage = "Percentage must be between 0 and 100.")]
        public decimal Percentage { get; set; }
        public bool IsActive { get; set; } = true;
    }

    public class TaxRuleUpdateDto : TaxRuleCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class TaxRuleResponseDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public decimal Percentage { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}