// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>
//
// Piece 6 (People/HR & ERP Integrations) note: several Create/Update shapes below were trimmed
// from the original generated (Update inherits Create) shape. Two different reasons, same fix:
//   - Identity/ownership anchors (CustomerProfileId, StaffProfileId, UserId) never change after
//     creation via these endpoints — same "TripId/BookingId/CustomerProfileId deliberately never
//     touched" pattern already used by ReviewUpdateDto/ComplaintUpdateDto (Piece 4).
//   - BusOperatorId on Agent/StaffProfile is the actual security boundary an operator's own staff
//     could otherwise abuse (create a profile/agent under a DIFFERENT operator, or move an
//     existing one) — dropped from Update entirely, and the value passed to Create is verified/
//     overridden server-side by the controller rather than trusted as-is.
//   - CustomerProfile.WalletBalance is dropped from Create/Update outright, for anyone, Admin
//     included — CustomerWalletService is the only code allowed to change it (see its class
//     comment); exposing it on a plain CRUD DTO would let a client set their own wallet balance.

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class AgentCreateDto
    {
        // Verified/overridden server-side for an operator's own staff — see AgentsController.
        public Guid? BusOperatorId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string Name { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(40)]
        public string AgencyCode { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string ContactPerson { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(30)]
        public string PhoneNumber { get; set; } = string.Empty;

        [StringLength(120)]
        [EmailAddress]
        public string? Email { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(250)]
        public string Address { get; set; } = string.Empty;

        [Range(0, 100, ErrorMessage = "CommissionPercentage must be between 0 and 100.")]
        public decimal CommissionPercentage { get; set; }
        public bool IsActive { get; set; } = true;
    }

    // BusOperatorId deliberately omitted — which operator this agent belongs to isn't something
    // a generic edit should be able to reassign (see AgentsController).
    public class AgentUpdateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string Name { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(40)]
        public string AgencyCode { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string ContactPerson { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(30)]
        public string PhoneNumber { get; set; } = string.Empty;

        [StringLength(120)]
        [EmailAddress]
        public string? Email { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(250)]
        public string Address { get; set; } = string.Empty;

        [Range(0, 100, ErrorMessage = "CommissionPercentage must be between 0 and 100.")]
        public decimal CommissionPercentage { get; set; }
        public bool IsActive { get; set; } = true;

        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class AgentResponseDto
    {
        public Guid Id { get; set; }
        public Guid? BusOperatorId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string AgencyCode { get; set; } = string.Empty;
        public string ContactPerson { get; set; } = string.Empty;
        public string PhoneNumber { get; set; } = string.Empty;
        public string? Email { get; set; }
        public string Address { get; set; } = string.Empty;
        public decimal CommissionPercentage { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // CustomerProfileId deliberately omitted — always resolved server-side from whoever is
    // logged in (see CustomerAddressesController), same idea as Booking/Complaint/Review never
    // trusting a client-supplied ownership id.
    public class CustomerAddressCreateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(40)]
        public string Label { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(250)]
        public string AddressLine { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string City { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string District { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string Country { get; set; } = "Bangladesh";
        public bool IsDefault { get; set; }
    }

    public class CustomerAddressUpdateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(40)]
        public string Label { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(250)]
        public string AddressLine { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string City { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string District { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(80)]
        public string Country { get; set; } = "Bangladesh";
        public bool IsDefault { get; set; }

        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CustomerAddressResponseDto
    {
        public Guid Id { get; set; }
        public Guid CustomerProfileId { get; set; }
        public string Label { get; set; } = string.Empty;
        public string AddressLine { get; set; } = string.Empty;
        public string City { get; set; } = string.Empty;
        public string District { get; set; } = string.Empty;
        public string Country { get; set; } = "Bangladesh";
        public bool IsDefault { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // UserId is trusted as-is only for Admin/Staff (creating a profile on someone else's
    // behalf); a plain customer's own UserId is forced server-side. WalletBalance is never
    // settable here at all — see file header.
    public class CustomerProfileCreateDto
    {
        public Guid UserId { get; set; }

        [StringLength(30)]
        public string? NationalIdNumber { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        public Gender Gender { get; set; } = Gender.Unknown;

        [StringLength(30)]
        public string? EmergencyContactPhone { get; set; }

        [StringLength(10)]
        public string? PreferredLanguageCode { get; set; }
    }

    // UserId and WalletBalance both omitted — which login this profile belongs to never
    // changes after creation, and WalletBalance is CustomerWalletService's alone to write.
    public class CustomerProfileUpdateDto
    {
        [StringLength(30)]
        public string? NationalIdNumber { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        public Gender Gender { get; set; } = Gender.Unknown;

        [StringLength(30)]
        public string? EmergencyContactPhone { get; set; }

        [StringLength(10)]
        public string? PreferredLanguageCode { get; set; }

        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class CustomerProfileResponseDto
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public string? NationalIdNumber { get; set; }
        public DateOnly? DateOfBirth { get; set; }
        public Gender Gender { get; set; } = Gender.Unknown;
        public string? EmergencyContactPhone { get; set; }
        public decimal WalletBalance { get; set; }
        public string? PreferredLanguageCode { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO: CustomerWalletService.CreditAsync/DebitAsync is the only writer,
    // and it always writes the balance change and this row together. CustomerWalletTransactionsController
    // is read-only.
    public class CustomerWalletTransactionResponseDto
    {
        public Guid Id { get; set; }
        public Guid CustomerProfileId { get; set; }
        public Guid? BookingId { get; set; }
        public Guid? RefundId { get; set; }
        public CustomerWalletTransactionType TransactionType { get; set; }
        public decimal Amount { get; set; }
        public decimal BalanceAfter { get; set; }
        public string Currency { get; set; } = "BDT";
        public string? Description { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // StaffProfileId (which employee this license belongs to) is verified against the caller's
    // own operator scope server-side — see DriverLicensesController.
    public class DriverLicenseCreateDto
    {
        public Guid StaffProfileId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(40)]
        public string LicenseNumber { get; set; } = string.Empty;
        public LicenseType Type { get; set; }
        public DateOnly IssueDate { get; set; }
        public DateOnly ExpiryDate { get; set; }
    }

    // StaffProfileId omitted — re-pointing a license to a different employee isn't an edit,
    // it's a new record.
    public class DriverLicenseUpdateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(40)]
        public string LicenseNumber { get; set; } = string.Empty;
        public LicenseType Type { get; set; }
        public DateOnly IssueDate { get; set; }
        public DateOnly ExpiryDate { get; set; }

        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class DriverLicenseResponseDto
    {
        public Guid Id { get; set; }
        public Guid StaffProfileId { get; set; }
        public string LicenseNumber { get; set; } = string.Empty;
        public LicenseType Type { get; set; }
        public DateOnly IssueDate { get; set; }
        public DateOnly ExpiryDate { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // CustomerProfileId deliberately omitted — same reasoning as CustomerAddressCreateDto above.
    public class EmergencyContactCreateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string Name { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(30)]
        public string Phone { get; set; } = string.Empty;

        [StringLength(60)]
        public string? Relation { get; set; }
    }

    public class EmergencyContactUpdateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string Name { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(30)]
        public string Phone { get; set; } = string.Empty;

        [StringLength(60)]
        public string? Relation { get; set; }

        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class EmergencyContactResponseDto
    {
        public Guid Id { get; set; }
        public Guid CustomerProfileId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Phone { get; set; } = string.Empty;
        public string? Relation { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SalesCounterCreateDto
    {
        public Guid BusOperatorId { get; set; }
        public Guid TerminalId { get; set; }
        public Guid? OperatorBranchId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(120)]
        public string CounterName { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(30)]
        public string CounterCode { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(30)]
        public string PhoneNumber { get; set; } = string.Empty;

        [Required(AllowEmptyStrings = false)]
        [StringLength(250)]
        public string Address { get; set; } = string.Empty;
        public bool IsActive { get; set; } = true;
    }

    public class SalesCounterUpdateDto : SalesCounterCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class SalesCounterResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public Guid TerminalId { get; set; }
        public Guid? OperatorBranchId { get; set; }
        public string CounterName { get; set; } = string.Empty;
        public string CounterCode { get; set; } = string.Empty;
        public string PhoneNumber { get; set; } = string.Empty;
        public string Address { get; set; } = string.Empty;
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // Chunk 6 task 1 — GET /api/salescounters/dashboard. One scoped server aggregate
    // instead of the counter desk downloading full booking/cancellation/complaint lists just
    // to count them client-side. "Date" is always a Bangladesh local (Asia/Dhaka) calendar
    // day — see SalesCountersController.GetDashboard's own comment on why.
    public class CounterDashboardResponseDto
    {
        public DateOnly Date { get; set; }

        // Totals across every counter this caller can see (see GetDashboard's scoping
        // comment) — same numbers as summing Counters below, provided as a convenience so a
        // CounterStaff member watching their own single counter doesn't have to add it up.
        public int TicketsSoldToday { get; set; }
        public decimal CashSalesTotal { get; set; }

        [MaxLength(3)]
        public string Currency { get; set; } = "BDT";

        public int PendingCancellations { get; set; }
        public int OpenComplaints { get; set; }

        public IReadOnlyCollection<CounterDashboardCounterSummaryDto> Counters { get; set; } =
            Array.Empty<CounterDashboardCounterSummaryDto>();
    }

    public class CounterDashboardCounterSummaryDto
    {
        public Guid CounterId { get; set; }
        public string CounterName { get; set; } = string.Empty;
        public string CounterCode { get; set; } = string.Empty;
        public int TicketsSoldToday { get; set; }
        public decimal CashSalesTotal { get; set; }
    }

    // StaffProfileId verified against the caller's own operator scope server-side — see
    // StaffAttendancesController.
    public class StaffAttendanceCreateDto
    {
        public Guid StaffProfileId { get; set; }
        public DateOnly AttendanceDate { get; set; }
        public AttendanceStatus Status { get; set; }

        [StringLength(250)]
        public string? Remarks { get; set; }
    }

    public class StaffAttendanceUpdateDto
    {
        public DateOnly AttendanceDate { get; set; }
        public AttendanceStatus Status { get; set; }

        [StringLength(250)]
        public string? Remarks { get; set; }

        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class StaffAttendanceResponseDto
    {
        public Guid Id { get; set; }
        public Guid StaffProfileId { get; set; }
        public DateOnly AttendanceDate { get; set; }
        public AttendanceStatus Status { get; set; }
        public string? Remarks { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // BusOperatorId verified/overridden server-side for an operator's own staff — see
    // StaffProfilesController. This is the actual security boundary in this bucket: without the
    // check, an operator's own staff could plant a profile under a different operator (or under
    // no operator at all, i.e. platform-staff scope).
    public class StaffProfileCreateDto
    {
        public Guid UserId { get; set; }
        public Guid? BusOperatorId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(50)]
        public string EmployeeCode { get; set; } = string.Empty;
        public StaffRole Role { get; set; }

        [StringLength(30)]
        public string? NationalIdNumber { get; set; }
        public DateOnly? JoiningDate { get; set; }

        [StringLength(250)]
        public string? Address { get; set; }

        [Range(0, int.MaxValue)]
        public int TotalTripsCompleted { get; set; }
        public bool IsActive { get; set; } = true;
    }

    // UserId and BusOperatorId both omitted — which login this profile is attached to, and
    // which operator (if any) it belongs to, are never reassignable via a generic edit.
    public class StaffProfileUpdateDto
    {
        [Required(AllowEmptyStrings = false)]
        [StringLength(50)]
        public string EmployeeCode { get; set; } = string.Empty;
        public StaffRole Role { get; set; }

        [StringLength(30)]
        public string? NationalIdNumber { get; set; }
        public DateOnly? JoiningDate { get; set; }

        [StringLength(250)]
        public string? Address { get; set; }

        [Range(0, int.MaxValue)]
        public int TotalTripsCompleted { get; set; }
        public bool IsActive { get; set; } = true;

        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // RBAC Amendment v3, task 5: "provide a limited 'my profile' DTO for permitted contact
    // fields only". Deliberately excludes EmployeeCode, Role, IsActive, TotalTripsCompleted —
    // anyone can update their own contact details without holding Staff.Manage, but only
    // Staff.Manage (via the full StaffProfileUpdateDto above) can change job-affecting fields,
    // and even then never on your OWN profile (see StaffProfilesController.Update's
    // self-promotion guard).
    public class StaffProfileMyProfileUpdateDto
    {
        [StringLength(30)]
        public string? NationalIdNumber { get; set; }

        [StringLength(250)]
        public string? Address { get; set; }

        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

  public class StaffProfileResponseDto
  {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public Guid? BusOperatorId { get; set; }
        public string EmployeeCode { get; set; } = string.Empty;
        public StaffRole Role { get; set; }
        public string? NationalIdNumber { get; set; }
        public DateOnly? JoiningDate { get; set; }
        public string? Address { get; set; }
        public int TotalTripsCompleted { get; set; }
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // StaffProfileId verified against the caller's own operator scope server-side — see
    // StaffSalariesController.
    public class StaffSalaryCreateDto
    {
        public Guid StaffProfileId { get; set; }
        public DateOnly PayPeriodStart { get; set; }
        public DateOnly PayPeriodEnd { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "Amount cannot be negative.")]
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
        public DateTime? PaidAtUtc { get; set; }

        [StringLength(120)]
        public string? PaymentReference { get; set; }
    }

    public class StaffSalaryUpdateDto
    {
        public DateOnly PayPeriodStart { get; set; }
        public DateOnly PayPeriodEnd { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "Amount cannot be negative.")]
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
        public DateTime? PaidAtUtc { get; set; }

        [StringLength(120)]
        public string? PaymentReference { get; set; }

        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class StaffSalaryResponseDto
    {
        public Guid Id { get; set; }
        public Guid StaffProfileId { get; set; }
        public DateOnly PayPeriodStart { get; set; }
        public DateOnly PayPeriodEnd { get; set; }
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
        public DateTime? PaidAtUtc { get; set; }
        public string? PaymentReference { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}
