// <auto-generated>
// Generated to give every remaining entity a working CRUD API for Swagger/Postman.
// Simple flat Create/Update/Response DTOs — one-to-one with the entity's own scalar fields.
// </auto-generated>

using TicketPortal.Api.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace TicketPortal.Api.DTO
{
    public class ScheduleCreateDto
    {
        public Guid BusOperatorId { get; set; }
        public Guid BusRouteId { get; set; }
        public Guid? OperatorRouteId { get; set; }
        public Guid BusId { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(40)]
        public string ScheduleCode { get; set; } = string.Empty;
        public TimeSpan DepartureTimeOfDay { get; set; }
        public TimeSpan? ArrivalTimeOfDay { get; set; }
        public DayOfWeekFlag OperatingDays { get; set; } = DayOfWeekFlag.Everyday;
        public DateOnly EffectiveFrom { get; set; }
        public DateOnly? EffectiveTo { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "BaseFare cannot be negative.")]
        public decimal BaseFare { get; set; }

        [Required(AllowEmptyStrings = false)]
        [StringLength(3, MinimumLength = 3)]
        public string Currency { get; set; } = "BDT";
        public bool IsActive { get; set; } = true;
    }

    public class ScheduleUpdateDto : ScheduleCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class ScheduleResponseDto
    {
        public Guid Id { get; set; }
        public Guid BusOperatorId { get; set; }
        public Guid BusRouteId { get; set; }
        public Guid? OperatorRouteId { get; set; }
        public Guid BusId { get; set; }
        public string ScheduleCode { get; set; } = string.Empty;
        public TimeSpan DepartureTimeOfDay { get; set; }
        public TimeSpan? ArrivalTimeOfDay { get; set; }
        public DayOfWeekFlag OperatingDays { get; set; } = DayOfWeekFlag.Everyday;
        public DateOnly EffectiveFrom { get; set; }
        public DateOnly? EffectiveTo { get; set; }
        public decimal BaseFare { get; set; }
        public string Currency { get; set; } = "BDT";
        public bool IsActive { get; set; } = true;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class TripCrewCreateDto
    {
        public Guid TripId { get; set; }
        public Guid StaffProfileId { get; set; }
        public CrewRole Role { get; set; }
        public DateTime AssignedAtUtc { get; set; } = DateTime.UtcNow;
    }

    public class TripCrewUpdateDto : TripCrewCreateDto
    {
        // Required — optimistic-concurrency token, echo back what GET returned.
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    public class TripCrewResponseDto
    {
        public Guid Id { get; set; }
        public Guid TripId { get; set; }
        public Guid StaffProfileId { get; set; }
        public CrewRole Role { get; set; }
        public DateTime AssignedAtUtc { get; set; } = DateTime.UtcNow;
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

    // No Create/Update DTO: this is the append-only trail of a Trip's own status changes,
    // written only from TripsController wherever Trip.Status actually changes.
    // TripStatusHistoriesController is read-only, Admin/Staff-only.
    public class TripStatusHistoryResponseDto
    {
        public Guid Id { get; set; }
        public Guid TripId { get; set; }
        public Guid? ChangedByUserId { get; set; }
        public TripStatus Status { get; set; }
        public DateTime ChangedAtUtc { get; set; } = DateTime.UtcNow;
        public string? Remarks { get; set; }
        public DateTime CreatedAtUtc { get; set; }
        public DateTime? UpdatedAtUtc { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();
    }

}