import { api } from "@/lib/api";
import type { OperatorStatement, OperatorStatementDetail } from "@/types/operatorStatement";

const BASE = "/api/OperatorStatements";

// Read-only — see class comment on OperatorStatementsController (generated by
// SettlementGenerationService alongside its OperatorSettlement, never created/edited by hand).
export const operatorStatementService = {
  getAll: (busOperatorId?: string) =>
    api
      .get<OperatorStatement[]>(BASE, { params: busOperatorId ? { busOperatorId } : undefined })
      .then((r) => r.data),
  getById: (id: string) => api.get<OperatorStatementDetail>(`${BASE}/${id}`).then((r) => r.data),
};